kuntries={"USA":"Washington D.C",
          "UK":"London",
          "Russia":"Moscow",
          "China":"Beijing",
          "Australia":"Canberra",
          "France":"Paris",
          "Germany":"Berlin",
          "Pakistan":"Islamabad",
          "Egypt":"Cairo",
          "Saudi Arabia":"Riyadh",
          "Turkey":"Istanbul",
          "India":"New Delhi",
          "Nigeria":"Lagos",
          "Serbia":"Belgrade",
          "Italy":"Rome",
          "Japan":"Tokyo",
          "Poland":"Warsaw",
          "Afghanistan":"Kabul",
          "Netherlands":"Amsterdam",
          "Vietnam":"Ho Chi Minh City"}
print(kuntries["Poland"])
print(kuntries)